module.exports = {
  GET_ERRORS: "GET_ERRORS",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  PROFIlE_LOADING: "PROFILE_LOADING",
  GET_PROFILE: "GET_PROFILE",
  PROFILE_NOT_COUNT: "PROFILE_NOT_COUNT",
  SET_CURRENT_USER: "SET_CURRENT-USER",
  CLEAR_CURRENT_PROFILE: "CLEAR_CURRENT_PROFILE",
};
